# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiceUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets,QtCore,QtGui
from PyQt5.QtGui import QMovie
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.uic import loadUiType

class Ui_Background(object):
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5 import QtWidgets,QtCore,QtGui
    from PyQt5.QtGui import QMovie, QIcon
    from PyQt5.QtWidgets import QMainWindow
    import random
    def setupUi(self, Background):
        Background.setObjectName("Background")
        Background.resize(800, 600)
        Background.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Background)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -1, 821, 661))
        self.label.setStyleSheet("\n"
"font: 20pt \"Algerian\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 200, 171, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(325, 380, 121, 22))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Algerian\";\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(325, 410, 121, 22))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"Algerian\";")
        self.pushButton_2.setObjectName("pushButton_2")
        Background.setCentralWidget(self.centralwidget)

        self.retranslateUi(Background)
        QtCore.QMetaObject.connectSlotsByName(Background)

        self.pushButton.clicked.connect(self.roll)
        self.pushButton_2.clicked.connect(self.stop)

    def retranslateUi(self, Background):
        _translate = QtCore.QCoreApplication.translate
        Background.setWindowTitle(_translate("Background", "DICE"))
        self.pushButton.setText(_translate("Background", "ROLL"))
        self.pushButton_2.setText(_translate("Background", "STOP"))
        Background.setWindowIcon(QIcon("icon.png"))
    
#    def animation(self):
#            self.ui.movie = Qt.Gui.QMovie("C:\Users\Jatin Dhall\Desktop\CS\PYTHON\PYTHON PROJECTSS\Dice\Rolling animation.gif")
#            self.ui.self.setMovie(self.ui.movie)
#            self.ui.movie.start()

    def roll(self):
        #self.label_2.setPixmap(QtGui.QPixmap("Rolling animation.gif"))
        self.movie = self.QMovie("Rolling animation.gif")
        self.label_2.setMovie(self.movie)
        self.movie.start()

    def stop(self):
        self.ans=self.dice()
        #self.mov=self.roll()
        #self.mov.setPaused()
        if self.ans==1:
            self.label_2.setPixmap(QtGui.QPixmap("1.png"))
        elif self.ans==2:
            self.label_2.setPixmap(QtGui.QPixmap("2.png"))
        elif self.ans==3:
            self.label_2.setPixmap(QtGui.QPixmap("3.png"))
        elif self.ans==4:
            self.label_2.setPixmap(QtGui.QPixmap("4.png"))
        elif self.ans==5:
            self.label_2.setPixmap(QtGui.QPixmap("5.png"))
        elif self.ans==6:
            self.label_2.setPixmap(QtGui.QPixmap("6.png"))

    def dice(self):
        self.ans=self.random.randint(1,6)
        return self.ans


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Background = QtWidgets.QMainWindow()
    ui = Ui_Background()
    ui.setupUi(Background)
    Background.show()
    sys.exit(app.exec_())
